thumbnail:
    typst compile --root . --pages 1 template/main.typ thumbnail.png

install namespace="local":
    typst-pkg-installer --namespace {{namespace}} install
    
link namespace="local":
    typst-pkg-installer --namespace {{namespace}} link

remove namespace="local":
    typst-pkg-installer --namespace {{namespace}} remove

ls namespace="local":
    typst-pkg-installer --namespace {{namespace}} ls