[package]
name = "heiafr-report"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Jacques Supcik <jacques.supcik@hefr.ch>"]
license = "MIT"
description = "Typst template for letters at HEIA-FR"

[template]
path = "template"
entrypoint = "main.typ"
