boot.cifs: boot_cifs.cmd
	mkimage -T script -A arm -C none -d boot_cifs.cmd boot.cifs

boot.net: boot_net.cmd
	mkimage -T script -A arm -C none -d boot_net.cmd boot.net

boot.emmc: boot_emmc.cmd
	mkimage -T script -A arm -C none -d boot_emmc.cmd boot.emmc